In [1]:
import pandas as pd

In [18]:
import numpy as np

In [17]:
from pandas import Series,DataFrame

In [3]:
obj=Series([4,9,-69,58])

In [4]:
obj

0     4
1     9
2   -69
3    58
dtype: int64

In [5]:
obj.values

array([  4,   9, -69,  58], dtype=int64)

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2=Series([2,6,8,8,7],['k','d','f','d','fr'])

In [8]:
obj2

k     2
d     6
f     8
d     8
fr    7
dtype: int64

In [9]:
obj2.index

Index(['k', 'd', 'f', 'd', 'fr'], dtype='object')

In [10]:
obj2=Series([2,6,8,8,7],['k','d','f','d'])

ValueError: Length of passed values is 5, index implies 4

In [12]:
obj2[obj2<0]

Series([], dtype: int64)

Series 可以看做一种字典

In [13]:
data={'as':25,255:266}

In [14]:
obj3=Series(data)

In [15]:
obj3

as      25
255    266
dtype: int64

In [20]:
np.exp(obj3)

as      7.200490e+10
255    3.329141e+115
dtype: float64

In [21]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [24]:
states = ['California', 'Ohjio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, states)
obj4

California        NaN
Ohjio             NaN
Oregon        16000.0
Texas         71000.0
dtype: float64

In [25]:
pd.isnull(obj4)

California     True
Ohjio          True
Oregon        False
Texas         False
dtype: bool

In [26]:
pd.notnull(obj4)

California    False
Ohjio         False
Oregon         True
Texas          True
dtype: bool

In [27]:
obj3

as      25
255    266
dtype: int64

In [28]:
obj3+obj4

255          NaN
California   NaN
Ohjio        NaN
Oregon       NaN
Texas        NaN
as           NaN
dtype: float64

In [29]:
obj4.name

In [30]:
obj4

California        NaN
Ohjio             NaN
Oregon        16000.0
Texas         71000.0
dtype: float64

In [33]:
obj4.name='population'

In [34]:
obj4

California        NaN
Ohjio             NaN
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [35]:
obj

0     4
1     9
2   -69
3    58
dtype: int64

In [36]:
obj.index=['sd']

ValueError: Length mismatch: Expected axis has 4 elements, new values have 1 elements

In [37]:
obj
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob       4
Steve     9
Jeff    -69
Ryan     58
dtype: int64

In [38]:
vdata = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [39]:
data

{'as': 25, 255: 266}

In [40]:
vdata

{'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [41]:
vdata.shape

AttributeError: 'dict' object has no attribute 'shape'

In [42]:
frame=DataFrame(vdata)

In [43]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [44]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [49]:
DataFrame(vdata,columns=['year','state'])

year   state
0  2000    Ohio
1  2001    Ohio
2  2002    Ohio
3  2001  Nevada
4  2002  Nevada
5  2003  Nevada

In [51]:
frame2 = pd.DataFrame(vdata, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four',
                             'five', 'six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [52]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [53]:
frame2.index

Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')

In [74]:
print(frame2['year'].index.name)

None


In [75]:
frame2.loc('three')

ValueError: No axis named three for object type <class 'type'>

In [76]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [77]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [94]:
frame2['debt']=np.arange(6)

In [95]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4
six    2003  Nevada  3.2     5

In [97]:
val=Series([-26,-56,48],['two','four','ffd'])

In [98]:
frame2['debt']=val

In [99]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7 -26.0
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4 -56.0
five   2002  Nevada  2.9   NaN
six    2003  Nevada  3.2   NaN

In [102]:
frame2['eastern'] = frame2.state == 'Ohio'

In [103]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7 -26.0     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4 -56.0    False
five   2002  Nevada  2.9   NaN    False
six    2003  Nevada  3.2   NaN    False

In [104]:
frame2.eastern

one       True
two       True
three     True
four     False
five     False
six      False
Name: eastern, dtype: bool

In [105]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [106]:
np

<module 'numpy' from 'D:\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

In [107]:
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [113]:
np.array(pop)

array({'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}},
      dtype=object)

AttributeError: 'dict' object has no attribute 'shape'

In [114]:
frame3=DataFrame(pop)

In [115]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [116]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [117]:
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [125]:
pdata = {frame3.Ohio[:-1],
          frame3.Nevada[:2]}
DataFrame(pdata)

TypeError: 'Series' objects are mutable, thus they cannot be hashed

In [120]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [126]:
frame3.index.name = 'year'; frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [127]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [128]:
frame2.values

array([[2000, 'Ohio', 1.5, nan, True],
       [2001, 'Ohio', 1.7, -26.0, True],
       [2002, 'Ohio', 3.6, nan, True],
       [2001, 'Nevada', 2.4, -56.0, False],
       [2002, 'Nevada', 2.9, nan, False],
       [2003, 'Nevada', 3.2, nan, False]], dtype=object)

In [129]:
frame2.values.shape

(6, 5)

In [130]:
frame2.index

Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')

In [132]:
obj = pd.Series(range(3), ['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [133]:
index[1:]

Index(['b', 'c'], dtype='object')

In [134]:
index[1] = 'd'

TypeError: Index does not support mutable operations

In [135]:
Series(obj,['d','g','h'])

d   NaN
g   NaN
h   NaN
dtype: float64

In [136]:
obj

a    0
b    1
c    2
dtype: int64

In [137]:
labels=pd.Index(np.arange(3))

In [139]:
obj2=Series([60,22,45],labels)

In [140]:
obj2

0    60
1    22
2    45
dtype: int64

name,label 会自动转换为index，immutable

In [144]:
frame3.columns.any(['Nevada', 'Ohio'])

'Nevada'

In [145]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [146]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [148]:
obj3=Series(obj,['a', 'b', 'c', 'd', 'e'])

In [149]:
obj3

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [150]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [151]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3


0      blue
2    purple
4    yellow
dtype: object

In [153]:
obj3.reindex(np.arange(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [154]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [155]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [156]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [157]:
frame.loc[['a', 'b', 'c', 'd'], states]

D:\Anaconda3\lib\site-packages\pandas\core\indexing.py:1494: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)


Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [158]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [159]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [160]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [161]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [162]:
data.T

Ohio  Colorado  Utah  New York
one       0         4     8        12
two       1         5     9        13
three     2         6    10        14
four      3         7    11        15

In [163]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [164]:
data.drop( axis=1)

ValueError: Need to specify at least one of 'labels', 'index' or 'columns'

In [165]:
data.drop('two')

KeyError: "['two'] not found in axis"

In [166]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [170]:
data.drop(axis=0)

ValueError: Need to specify at least one of 'labels', 'index' or 'columns'

In [171]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [172]:
data.drop('one',axis=1,inplace=True)

In [173]:
data

two  three  four
Ohio        1      2     3
Colorado    5      6     7
Utah        9     10    11
New York   13     14    15

In [174]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [175]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [176]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [180]:
obj['b':'d']

b    1.0
c    2.0
d    3.0
dtype: float64

In [181]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [182]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [184]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [189]:
data.loc[:2]

TypeError: cannot do slice indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [2] of <class 'int'>

In [187]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [188]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [192]:
data[data['three']>10]

one  two  three  four
New York   12   13     14    15

In [195]:
data[['one','four']]

one  four
Ohio        0     3
Colorado    4     7
Utah        8    11
New York   12    15

In [196]:
data.loc['one']

KeyError: 'one'

In [197]:
data


one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [200]:
data.loc['Colorado']

one      4
two      5
three    6
four     7
Name: Colorado, dtype: int32

In [201]:
data.loc[:'Utah', 'two']

Ohio        1
Colorado    5
Utah        9
Name: two, dtype: int32

In [213]:
data.iloc[2:,:3][data.Utah>5]

AttributeError: 'DataFrame' object has no attribute 'Utah'

In [214]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [215]:
ser = pd.Series(np.arange(3.))

In [217]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [218]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
ser2[-1]

2.0

In [219]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [220]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [223]:
df1.add(df2,fill_value=0)

b    c     d     e
Colorado  6.0  7.0   8.0   NaN
Ohio      3.0  1.0   6.0   5.0
Oregon    9.0  NaN  10.0  11.0
Texas     9.0  4.0  12.0   8.0
Utah      0.0  NaN   1.0   2.0

In [224]:
arr = np.arange(12.).reshape((3, 4))
arr
arr[0]
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [225]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.iloc[0]

In [226]:
frame
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [227]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [228]:
series3 = frame['d']

In [229]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [230]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                      'c': [-2, 5, 8, -2.5]})
frame
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [231]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [232]:
obj.index.is_unique

False

In [233]:
obj['a']
obj['c']

4

In [234]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])
df

0         1         2
a  1.421449  1.076106 -0.514290
a  0.250303  0.455986  0.506952
b  0.701413 -0.238669  0.804414
b  0.304738 -0.373206  1.620107

In [235]:
df.loc['b']

0         1         2
b  0.701413 -0.238669  0.804414
b  0.304738 -0.373206  1.620107

In [236]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [237]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [238]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [239]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [240]:
df.idxmax()

one    b
two    d
dtype: object

In [242]:
price = pd.read_pickle('examples/yahoo_price.pkl')
volume = pd.read_pickle('examples/yahoo_volume.pkl')

FileNotFoundError: [Errno 2] No such file or directory: 'examples/yahoo_price.pkl'

In [246]:
import pandas_datareader.data as web

In [247]:
all_data = {ticker: web.get_data_yahoo(ticker) for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

In [248]:
price = pd.DataFrame({ticker: data['Adj Close'] for ticker, data in all_data.items()}) volume = pd.DataFrame({ticker: data['Volume'] for ticker, data in all_data.items()})

SyntaxError: invalid syntax (<ipython-input-248-c09ef6b977ed>, line 1)

In [ ]:
returns = price.pct_change()
returns.tail()

In [ ]:
returns['MSFT'].corr(returns['IBM'])
returns['MSFT'].cov(returns['IBM'])

In [ ]:
returns.MSFT.corr(returns.IBM)

In [ ]:
returns.corr()

In [ ]:
returns.corrwith(returns.IBM)

In [ ]:
import pandas_datareader.data as web all_data = {ticker: web.get_data_yahoo(ticker) for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

In [249]:
price = pd.DataFrame({ticker: data['Adj Close'] for ticker, data in all_data.items()}) volume = pd.DataFrame({ticker: data['Volume'] for ticker, data in all_data.items()})

SyntaxError: invalid syntax (<ipython-input-249-c09ef6b977ed>, line 1)

In [250]:
all_data

{'AAPL':                   High         Low        Open       Close       Volume  \
 Date                                                                      
 2009-12-31   30.478571   30.080000   30.447144   30.104286   88102700.0   
 2010-01-04   30.642857   30.340000   30.490000   30.572857  123432400.0   
 2010-01-05   30.798571   30.464285   30.657143   30.625713  150476200.0   
 2010-01-06   30.747143   30.107143   30.625713   30.138571  138040000.0   
 2010-01-07   30.285715   29.864286   30.250000   30.082857  119282800.0   
 2010-01-08   30.285715   29.865715   30.042856   30.282858  111902700.0   
 2010-01-11   30.428572   29.778572   30.400000   30.015715  115557400.0   
 2010-01-12   29.967142   29.488571   29.884285   29.674286  148614900.0   
 2010-01-13   30.132856   29.157143   29.695715   30.092857  151473000.0   
 2010-01-14   30.065714   29.860001   30.015715   29.918571  108223500.0   
 2010-01-15   30.228571   29.410000   30.132856   29.418571  148516900.0   
 201

In [251]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [252]:
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [253]:
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [254]:
pd.value_counts(obj.values, sort=False)

b    2
c    3
a    3
d    1
dtype: int64

In [255]:
obj
mask = obj.isin(['b', 'c'])
mask
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [256]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
unique_vals = pd.Series(['c', 'b', 'a'])
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [257]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                     'Qu2': [2, 3, 1, 2, 3],
                     'Qu3': [1, 5, 2, 4, 4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [258]:
result = data.apply(pd.value_counts).fillna(0)
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [261]:
!cat examples/ex1.csv

'cat' 不是内部或外部命令，也不是可运行的程序
或批处理文件。


In [263]:
type examples/ex1.csv

SyntaxError: invalid syntax (<ipython-input-263-fcfc7a042fd0>, line 1)

如果在windows注意加r

In [279]:
df = pd.read_csv('examples/ex1.csv')
df

ParserError: Error tokenizing data. C error: Expected 1 fields in line 32, saw 2


In [280]:
pd.read_table('examples/ex1.csv', sep=',')

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead.
  """Entry point for launching an IPython kernel.


ParserError: Error tokenizing data. C error: Expected 1 fields in line 32, saw 2


In [282]:
pd.read_csv('examples/ex2.csv', header=None)
pd.read_csv('examples/ex2.csv', names=['a', 'b', 'c', 'd', 'message'])

FileNotFoundError: [Errno 2] File b'examples/ex2.csv' does not exist: b'examples/ex2.csv'

In [283]:
names = ['a', 'b', 'c', 'd', 'message']
pd.read_csv('examples/ex2.csv', names=names, index_col='message')

FileNotFoundError: [Errno 2] File b'examples/ex2.csv' does not exist: b'examples/ex2.csv'

In [284]:
parsed = pd.read_csv('examples/csv_mindex.csv',
                     index_col=['key1', 'key2'])
parsed

FileNotFoundError: [Errno 2] File b'examples/csv_mindex.csv' does not exist: b'examples/csv_mindex.csv'

In [285]:
list(open('examples/ex3.txt'))

FileNotFoundError: [Errno 2] No such file or directory: 'examples/ex3.txt'

In [286]:
pd.options.display.max_rows = 10

In [287]:
result = pd.read_csv('examples/ex6.csv')
result


FileNotFoundError: [Errno 2] File b'examples/ex6.csv' does not exist: b'examples/ex6.csv'

In [288]:
chunker = pd.read_csv('examples/ex6.csv', chunksize=1000)
chunker

FileNotFoundError: [Errno 2] File b'examples/ex6.csv' does not exist: b'examples/ex6.csv'

In [289]:
chunker = pd.read_csv('examples/ex6.csv', chunksize=1000)

tot = pd.Series([])
for piece in chunker:
    tot = tot.add(piece['key'].value_counts(), fill_value=0)

tot = tot.sort_values(ascending=False)

FileNotFoundError: [Errno 2] File b'examples/ex6.csv' does not exist: b'examples/ex6.csv'

In [290]:
tot[:10]

NameError: name 'tot' is not defined

In [291]:
data = pd.read_csv('examples/ex5.csv')
data

FileNotFoundError: [Errno 2] File b'examples/ex5.csv' does not exist: b'examples/ex5.csv'

In [292]:
data.to_csv('examples/out.csv')
!cat examples/out.csv


'cat' 不是内部或外部命令，也不是可运行的程序
或批处理文件。


In [293]:
import sys
data.to_csv(sys.stdout, sep='|')


|Qu1|Qu2|Qu3
0|1|2|1
1|3|3|5
2|4|1|2
3|3|2|4
4|4|3|4


In [294]:
data.to_csv(sys.stdout, na_rep='NULL')

,Qu1,Qu2,Qu3
0,1,2,1
1,3,3,5
2,4,1,2
3,3,2,4
4,4,3,4


In [295]:
data.to_csv(sys.stdout, index=False, header=False)


1,2,1
3,3,5
4,1,2
3,2,4
4,3,4


In [296]:
data.to_csv(sys.stdout, index=False, columns=['a', 'b', 'c'])

KeyError: "None of [Index(['a', 'b', 'c'], dtype='object')] are in the [columns]"

In [297]:
dates = pd.date_range('1/1/2000', periods=7)
ts = pd.Series(np.arange(7), index=dates)
ts.to_csv('examples/tseries.csv')
!cat examples/tseries.csv

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.
  This is separate from the ipykernel package so we can avoid doing imports until
'cat' 不是内部或外部命令，也不是可运行的程序
或批处理文件。


In [298]:
import sqlite3
query = """
CREATE TABLE test
(a VARCHAR(20), b VARCHAR(20),
 c REAL,        d INTEGER
);"""
con = sqlite3.connect('mydata.sqlite')
con.execute(query)
con.commit()

In [299]:
data = [('Atlanta', 'Georgia', 1.25, 6),
        ('Tallahassee', 'Florida', 2.6, 3),
        ('Sacramento', 'California', 1.7, 5)]
stmt = "INSERT INTO test VALUES(?, ?, ?, ?)"
con.executemany(stmt, data)
con.commit()

In [300]:
cursor = con.execute('select * from test')
rows = cursor.fetchall()
rows

[('Atlanta', 'Georgia', 1.25, 6),
 ('Tallahassee', 'Florida', 2.6, 3),
 ('Sacramento', 'California', 1.7, 5)]

In [301]:
cursor.description
pd.DataFrame(rows, columns=[x[0] for x in cursor.description])

a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5

In [302]:
import sqlalchemy as sqla
db = sqla.create_engine('sqlite:///mydata.sqlite')
pd.read_sql('select * from test', db)

a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5

In [303]:
!rm mydata.sqlite

'rm' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
